apiVersion: v1
kind: ReplicationController
metadata:
  name: mitsuba-spectral
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mitsuba-spectral
    spec:
      containers:
      - name: mitsuba-spectral-container
        image: ninjaben/mitsuba-spectral
        command: ['sleep', '1e6']
        volumeMounts:
        - mountPath: /data/shared
          name: data-shared
      volumes:
      - name: data-shared
        persistentVolumeClaim:
          claimName: data-shared-claim
