apiVersion: v1
kind: ReplicationController
metadata:
  name: pbrt-v2-spectral-spectral
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pbrt
    spec:
      containers:
      - name: pbrt-v2-spectral-container
        image: ninjaben/pbrt-v2-spectral-docker:latest
        command: ['sleep', '1e6']
        volumeMounts:
        - mountPath: /data/shared
          name: data-shared
      volumes:
      - name: data-shared
        persistentVolumeClaim:
          claimName: data-shared-claim
