kind: PersistentVolume
apiVersion: v1
metadata:
  name: working-volume
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/"
    server: 67.253.65.32

