kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-shared
  labels:
    type: nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/data/shared"
    server: gpc.sas.upenn.edu
